### ISSUE TITLE
关于无法指定转发的群和冲突及建议

### ISSUE THREAD

**Issue by yankedi** [flben233/qc2mc#1]
1. **当我解决了一起问题使得插件可以运行时我发现改插件会转发其他群的消息**
2. **当我初次添加此插件时报错了但当我移除此插件时:[LuckPerms - Mirai - 高级权限服务插件](https://mirai.mamoe.net/topic/68/luckperms-mirai-%E9%AB%98%E7%BA%A7%E6%9D%83%E9%99%90%E6%9C%8D%E5%8A%A1%E6%8F%92%E4%BB%B6/22?page=2) 问题才解决，如果是权限问题您应该说明如何在LuckPerms中配置改插件的权限或者在介绍该插件时明令禁用**
这个是②的报错
![image](https://user-images.githubusercontent.com/85004029/150626544-2706ef35-fd5f-49b3-8a4b-a5469dc7fdab.png)
**最后催一下从mc服务器转发回QQ群的功能**

**Comment by flben233** [comment]
很高兴看到您的反馈，LuckPerms我没有测试过，因此没有发现这个问题，十分抱歉。关于无法指定群号的问题正在排查，一会给您回复。

**Comment by flben233** [comment]
指定群的问题已经修复，请更新至最新的release。关于LuckPerms的问题还需要一段时间来排查
